### ISSUE TITLE
How can I build my own dataset?

### ISSUE THREAD

**Issue by kkchenlight** [DataCanvasIO/HyperGBM#100]
I want to build my dataset for my application， how can i build the dataset， is there any standard of HyperGBM for the input data，or any user guide can  help me figure out the question。 
thanks for your time

**Comment by lixfz** [comment]
HyperGBM is a automated machine learning (AutoML) toolkit designed for tabular data. It covers the complete end-to-end ML processing stages, consisting of data cleaning, preprocessing, feature generation and selection, model selection and hyperparameter optimization. See [QuickStart](https://hypergbm.readthedocs.io/en/latest/quick_start_python.html) as a start point.
