### ISSUE TITLE
我遇到个依赖问题

### ISSUE THREAD

**Issue by timor2015** [DataCanvasIO/HyperGBM#101]
在notebook中引用  from hypergbm import make_experiment  出现了错误
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[17], line 1
----> 1 from hypergbm import make_experiment

File ~\.conda\envs\hypergbm\lib\site-packages\hypergbm\__init__.py:7
      3 """
      4 
      5 """
      6 from hypernets.experiment import CompeteExperiment
----> 7 from .hyper_gbm import HyperGBM, HyperGBMEstimator, HyperGBMExplainer, HyperEstimator, HyperModel
      8 from .experiment import make_experiment
     10 from ._version import __version__

File ~\.conda\envs\hypergbm\lib\site-packages\hypergbm\hyper_gbm.py:12
     10 import re
     11 import time
---> 12 from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN
     13 from imblearn.under_sampling import RandomUnderSampler, NearMiss, TomekLinks, EditedNearestNeighbours
     14 from sklearn import pipeline as sk_pipeline

File ~\.conda\envs\hypergbm\lib\site-packages\imblearn\__init__.py:52
     48     sys.stderr.write("Partial import of imblearn during the build process.\n")
     49     # We are not importing the rest of scikit-learn during the build
     50     # process, as it may not be compiled yet
     51 else:
---> 52     from . import (
     53         combine,
     54         ensemble,
     55         exceptions,
     56         metrics,
     57         over_sampling,
     58         pipeline,
     59         tensorflow,
     60         under_sampling,
     61         utils,
     62     )
     63     from ._version import __version__
     64     from .base import FunctionSampler

File ~\.conda\envs\hypergbm\lib\site-packages\imblearn\combine\__init__.py:5
      1 """The :mod:`imblearn.combine` provides methods which combine
      2 over-sampling and under-sampling.
      3 """
----> 5 from ._smote_enn import SMOTEENN
      6 from ._smote_tomek import SMOTETomek
      8 __all__ = ["SMOTEENN", "SMOTETomek"]

File ~\.conda\envs\hypergbm\lib\site-packages\imblearn\combine\_smote_enn.py:12
      9 from sklearn.base import clone
     10 from sklearn.utils import check_X_y
---> 12 from ..base import BaseSampler
     13 from ..over_sampling import SMOTE
     14 from ..over_sampling.base import BaseOverSampler

File ~\.conda\envs\hypergbm\lib\site-packages\imblearn\base.py:21
     18 from sklearn.utils.multiclass import check_classification_targets
     20 from .utils import check_sampling_strategy, check_target_type
---> 21 from .utils._param_validation import validate_parameter_constraints
     22 from .utils._validation import ArraysTransformer
     25 class SamplerMixin(BaseEstimator, metaclass=ABCMeta):

File ~\.conda\envs\hypergbm\lib\site-packages\imblearn\utils\_param_validation.py:908
    906 from sklearn.utils._param_validation import generate_valid_param  # noqa
    907 from sklearn.utils._param_validation import validate_parameter_constraints  # noqa
--> 908 from sklearn.utils._param_validation import (
    909     HasMethods,
    910     Hidden,
    911     Interval,
    912     Options,
    913     StrOptions,
    914     _ArrayLikes,
    915     _Booleans,
    916     _Callables,
    917     _CVObjects,
    918     _InstancesOf,
    919     _IterablesNotString,
    920     _MissingValues,
    921     _NoneConstraint,
    922     _PandasNAConstraint,
    923     _RandomStates,
    924     _SparseMatrices,
    925     _VerboseHelper,
    926     make_constraint,
    927     validate_params,
    928 )

ImportError: cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\Users\fish\.conda\envs\hypergbm\lib\site-packages\sklearn\utils\_param_validation.py)

下面是 pip list
PS D:\codes\hyperGBM> pip list
Package                  Version
------------------------ ---------
anyio                    3.7.0
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
async-lru                2.0.2
attrs                    23.1.0
Babel                    2.12.1
backcall                 0.2.0
bcrypt                   4.0.1
beautifulsoup4           4.12.2
bleach                   6.0.0
catboost                 1.2
certifi                  2023.5.7
cffi                     1.15.1
charset-normalizer       3.1.0
click                    8.1.3
cloudpickle              2.2.1
colorama                 0.4.6
comm                     0.1.3
cryptography             41.0.1
cycler                   0.11.0
dask                     2023.6.1
dask-glm                 0.2.0
dask-ml                  2023.3.24
debugpy                  1.6.7
decorator                5.1.1
defusedxml               0.7.1
distributed              2023.6.1
exceptiongroup           1.1.1
executing                1.2.0
fastjsonschema           2.17.1
featuretools             1.26.0
fonttools                4.40.0
fqdn                     1.5.1
fsspec                   2023.6.0
graphviz                 0.20.1
hboard                   0.1.1
hboard-widget            0.1.1
holidays                 0.27.1
hypergbm                 0.2.5.7
hypernets                0.2.5.7
idna                     3.4
imbalanced-learn         0.10.1
importlib-metadata       6.7.0
importlib-resources      5.12.0
iniconfig                2.0.0
ipykernel                6.23.3
ipython                  8.14.0
ipywidgets               8.0.6
isoduration              20.11.0
jedi                     0.18.2
jieba                    0.42.1
Jinja2                   3.1.2
joblib                   1.3.1
json5                    0.9.14
jsonpointer              2.4
jsonschema               4.17.3
jupyter_client           8.3.0
jupyter_core             5.3.1
jupyter-events           0.6.3
jupyter-lsp              2.2.0
jupyter_server           2.7.0
jupyter_server_terminals 0.4.4
jupyterlab               4.0.2
jupyterlab-pygments      0.2.2
jupyterlab_server        2.23.0
jupyterlab-widgets       3.0.7
kiwisolver               1.4.4
lightgbm                 3.3.5
llvmlite                 0.40.1
locket                   1.0.0
MarkupSafe               2.1.3
matplotlib               3.5.3
matplotlib-inline        0.1.6
mistune                  3.0.1
msgpack                  1.0.5
multipledispatch         1.0.0
nbclient                 0.8.0
nbconvert                7.6.0
nbformat                 5.9.0
nest-asyncio             1.5.6
notebook_shim            0.2.3
numba                    0.57.1
numpy                    1.24.4
overrides                7.3.1
packaging                23.1
pandas                   1.5.3
pandocfilters            1.5.0
paramiko                 3.2.0
parso                    0.8.3
partd                    1.4.0
pickleshare              0.7.5
Pillow                   10.0.0
pip                      23.1.2
platformdirs             3.8.0
plotly                   5.15.0
pluggy                   1.2.0
prettytable              3.8.0
prometheus-client        0.17.0
prompt-toolkit           3.0.38
psutil                   5.9.5
pure-eval                0.2.2
pyarrow                  12.0.1
pycparser                2.21
Pygments                 2.15.1
PyNaCl                   1.5.0
pyparsing                3.1.0
pyrsistent               0.19.3
pytest                   7.4.0
python-dateutil          2.8.2
python-json-logger       2.0.7
pytz                     2023.3
pywin32                  306
pywinpty                 2.0.10
PyYAML                   6.0
pyzmq                    25.1.0
requests                 2.31.0
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
scikit-learn             1.2.0
scipy                    1.11.1
seaborn                  0.12.2
Send2Trash               1.8.2
setuptools               67.8.0
shap                     0.41.0
six                      1.16.0
slicer                   0.0.7
sniffio                  1.3.0
sortedcontainers         2.4.0
soupsieve                2.4.1
stack-data               0.6.2
tblib                    2.0.0
tenacity                 8.2.2
terminado                0.17.1
threadpoolctl            3.1.0
tinycss2                 1.2.1
tomli                    2.0.1
toolz                    0.12.0
tornado                  6.3.2
tqdm                     4.65.0
traitlets                5.9.0
typing_extensions        4.7.1
uri-template             1.3.0
urllib3                  2.0.3
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.6.1
wheel                    0.38.4
widgetsnbextension       4.0.7
woodwork                 0.24.0
xgboost                  1.7.6
XlsxWriter               3.1.2
zict                     3.0.0
zipp                     3.15.0

开始觉得可能是scikit-learn版本每对应上，我试了几个版本还是都报这个错误

**Comment by timor2015** [comment]
我重启了虚拟环境，这个错误没再出现了...

**Comment by lixfz** [comment]
imbalanced-learn与最新scikit-learn不兼容，可能是你之前安装过scikit-learn1.3导致的。
继续观察，如遇问题及时沟通
