### ISSUE TITLE
infer_task_type  Error inferring

### ISSUE THREAD

**Issue by jiapeijia** [DataCanvasIO/HyperGBM#33]
![image](https://user-images.githubusercontent.com/27725413/112938732-be42ce00-915c-11eb-8707-578f1240b82c.png)
![image](https://user-images.githubusercontent.com/27725413/112938904-1ed20b00-915d-11eb-8624-c396c1e4cb3d.png)

**Comment by lixfz** [comment]
Fixed.

Update latest hypernets and hypergbm, pls.
