### ISSUE TITLE
Same model got different result with PlaybackSearcher

### ISSUE THREAD

**Issue by Enpen** [DataCanvasIO/HyperGBM#45]
**System information**
- OS Platform and Distribution (e.g., CentOS 7.6): win10
- Python version: 3.6.7
- HyperGBM version: 0.2.3
- Other Python packages(run `pip list`):

**Describe the current behavior**
Hi, I got a nice lightgbm model using EvolutionSearcher, Then I used PlaybackSearcher to get cross-validation score, but I got a different score every time I run it. I found that the values of model's random_state are different.

**Describe the expected behavior**
For same hyper_model_.history, Get same reward using PlaybackSearcher.

**Standalone code to reproduce the issue**

```
import numpy as np
import pandas as pd
from hypernets.searchers import EvolutionSearcher
from hypergbm.search_space import GeneralSearchSpaceGenerator
from hypergbm import make_experiment
from hypernets.searchers import PlaybackSearcher
from hypernets.core.trial import TrialHistory
from hypernets.tabular.datasets import dsutils
train_data = dsutils.load_adult()
coloums_ = [f'feature{i}' for i in range(14)]+['target']
train_data.columns = coloums_
target = 'target'
print(train_data.shape)
history_file = 'history.txt'
search_space_ = GeneralSearchSpaceGenerator(
    n_estimators=600,
    enable_xgb=False,
    enable_catboost=False,
    
)
rs = EvolutionSearcher(search_space_,optimize_direction='max',population_size=50, sample_size=6, candidates_size=5)
exp = make_experiment(train_data.copy(),eval_data=None,test_data=None,target=target,max_trials=1,random_state=1,ensemble_size = 0, searcher=rs,log_level='info')
estimator = exp.run()
_,ensemble_model = estimator.steps[-1]
print(f'model\'s random_state is {ensemble_model.cv_gbm_models_[0].random_state}')
exp.hyper_model_.history.save(history_file)
 
 
history = TrialHistory.load_history(search_space_, history_file)
playback = PlaybackSearcher(history, top_n=1, optimize_direction='max')


exp = make_experiment(train_data.copy(),eval_data=None,test_data=None,target=target,max_trials=1,random_state=1,ensemble_size = 0,searcher=playback,log_level='info')
estimator = exp.run()
_,ensemble_model = estimator.steps[-1]
print(f'model\'s random_state is {ensemble_model.cv_gbm_models_[0].random_state}')
```

**Are you willing to submit PR?(Yes/No)**
Yes

**Other info / logs**

The process is as follows:

First:
![image](https://user-images.githubusercontent.com/26291393/136524601-5307d270-fc88-41c3-b0a3-4101a3aedaca.png)
Second:
![image](https://user-images.githubusercontent.com/26291393/136524633-e8b1eebe-fbd8-4520-acce-9dd3b417466d.png)

**Comment by lixfz** [comment]
When dumping TrailHistory as a text file, it is friendly to human reading, but it does not contain all the trial information, so the searching process cannot be completely reproduced in PlaybackSearcher. We recommand dumping the TrailHistory with `pickle` to playback it.

Since version 0.2.5, we add pickle support in TrailHistory `save` and `load` methods.  Change `history_file = 'history.txt'` to `history_file = 'history.pkl'` in your code to dump the full trial information, the PlaybackSearcher will reproduce the completely searching process.
