### ISSUE TITLE
Sklearn version conflict when I use hypergbm on kaggle

### ISSUE THREAD

**Issue by Enpen** [DataCanvasIO/HyperGBM#46]
**System information**
- OS Platform and Distribution (e.g., CentOS 7.6): Linux version 5.4.144+ (builder@27db0e08a636)
- Python version:
- HyperGBM version: 0.2.3
- Other Python packages(run `pip list`):

**Describe the current behavior**
I wanna use hypergbm on kaggle, but i got error, Looks like a version conflict

**Describe the expected behavior**
Just use !pip3 install -U hypergbm then i can use hypergbm on kaggle.

**Standalone code to reproduce the issue**
```
!pip3 install -U hypergbm
import hypergbm
```

**Are you willing to submit PR?(Yes/No)**

I notice here.
> Attempting uninstall: scikit-learn
> Found existing installation: scikit-learn 0.23.2
> Uninstalling scikit-learn-0.23.2:
> Successfully uninstalled scikit-learn-0.23.2

If add !pip3 install -U scikit-learn==0.23.2, it will be okay.

> Installing collected packages: scikit-learn
> Attempting uninstall: scikit-learn
> Found existing installation: scikit-learn 1.0
> Uninstalling scikit-learn-1.0:
> Successfully uninstalled scikit-learn-1.0

**Other info / logs**

> Collecting hypergbm
> Downloading hypergbm-0.2.3-py3-none-any.whl (2.9 MB)
> |████████████████████████████████| 2.9 MB 809 kB/s eta 0:00:01
> Requirement already satisfied: plotly in /opt/conda/lib/python3.7/site-packages (from hypergbm) (5.3.1)
> Requirement already satisfied: catboost>=0.26 in /opt/conda/lib/python3.7/site-packages (from hypergbm) (0.26.1)
> Requirement already satisfied: distributed in /opt/conda/lib/python3.7/site-packages (from hypergbm) (2021.9.0)
> Requirement already satisfied: dask in /opt/conda/lib/python3.7/site-packages (from hypergbm) (2021.9.0)
> Collecting hypernets==0.2.3
> Downloading hypernets-0.2.3-py3-none-any.whl (3.2 MB)
> |████████████████████████████████| 3.2 MB 54.2 MB/s eta 0:00:01
> Collecting dask-ml
> Downloading dask_ml-1.9.0-py3-none-any.whl (143 kB)
> |████████████████████████████████| 143 kB 64.3 MB/s eta 0:00:01
> Requirement already satisfied: xgboost>=1.3.0 in /opt/conda/lib/python3.7/site-packages (from hypergbm) (1.4.2)
> Requirement already satisfied: imbalanced-learn>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from hypergbm) (0.8.0)
> Requirement already satisfied: tqdm in /opt/conda/lib/python3.7/site-packages (from hypergbm) (4.62.1)
> Requirement already satisfied: fsspec>=0.8.0 in /opt/conda/lib/python3.7/site-packages (from hypergbm) (2021.8.1)
> Requirement already satisfied: lightgbm>=3.2.0 in /opt/conda/lib/python3.7/site-packages (from hypergbm) (3.2.1)
> Requirement already satisfied: scikit-learn>=0.22.1 in /opt/conda/lib/python3.7/site-packages (from hypernets==0.2.3->hypergbm) (0.23.2)
> Requirement already satisfied: numpy>=1.16.5 in /opt/conda/lib/python3.7/site-packages (from hypernets==0.2.3->hypergbm) (1.19.5)
> Requirement already satisfied: pandas>=0.25.3 in /opt/conda/lib/python3.7/site-packages (from hypernets==0.2.3->hypergbm) (1.3.2)
> Collecting seaborn==0.11.0
> Downloading seaborn-0.11.0-py3-none-any.whl (283 kB)
> |████████████████████████████████| 283 kB 64.3 MB/s eta 0:00:01
> Requirement already satisfied: pyarrow in /opt/conda/lib/python3.7/site-packages (from hypernets==0.2.3->hypergbm) (5.0.0)
> Requirement already satisfied: scipy in /opt/conda/lib/python3.7/site-packages (from hypernets==0.2.3->hypergbm) (1.7.1)
> Requirement already satisfied: featuretools in /opt/conda/lib/python3.7/site-packages (from hypernets==0.2.3->hypergbm) (0.27.1)
> Requirement already satisfied: ipython in /opt/conda/lib/python3.7/site-packages (from hypernets==0.2.3->hypergbm) (7.26.0)
> Collecting python-geohash
> Downloading python-geohash-0.8.5.tar.gz (17 kB)
> Requirement already satisfied: traitlets in /opt/conda/lib/python3.7/site-packages (from hypernets==0.2.3->hypergbm) (5.0.5)
> Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from hypernets==0.2.3->hypergbm) (1.15.0)
> Requirement already satisfied: matplotlib>=2.2 in /opt/conda/lib/python3.7/site-packages (from seaborn==0.11.0->hypernets==0.2.3->hypergbm) (3.4.3)
> Requirement already satisfied: graphviz in /opt/conda/lib/python3.7/site-packages (from catboost>=0.26->hypergbm) (0.8.4)
> Requirement already satisfied: joblib>=0.11 in /opt/conda/lib/python3.7/site-packages (from imbalanced-learn>=0.7.0->hypergbm) (1.0.1)
> Collecting scikit-learn>=0.22.1
> Downloading scikit_learn-1.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (23.1 MB)
> |████████████████████████████████| 23.1 MB 52.6 MB/s eta 0:00:01
> Requirement already satisfied: wheel in /opt/conda/lib/python3.7/site-packages (from lightgbm>=3.2.0->hypergbm) (0.37.0)
> Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn==0.11.0->hypernets==0.2.3->hypergbm) (2.8.0)
> Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn==0.11.0->hypernets==0.2.3->hypergbm) (8.2.0)
> Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn==0.11.0->hypernets==0.2.3->hypergbm) (2.4.7)
> Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn==0.11.0->hypernets==0.2.3->hypergbm) (0.10.0)
> Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn==0.11.0->hypernets==0.2.3->hypergbm) (1.3.1)
> Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.3->hypernets==0.2.3->hypergbm) (2021.1)
> Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from scikit-learn>=0.22.1->hypernets==0.2.3->hypergbm) (2.2.0)
> Requirement already satisfied: toolz>=0.8.2 in /opt/conda/lib/python3.7/site-packages (from dask->hypergbm) (0.11.1)
> Requirement already satisfied: cloudpickle>=1.1.1 in /opt/conda/lib/python3.7/site-packages (from dask->hypergbm) (1.6.0)
> Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.7/site-packages (from dask->hypergbm) (21.0)
> Requirement already satisfied: partd>=0.3.10 in /opt/conda/lib/python3.7/site-packages (from dask->hypergbm) (1.2.0)
> Requirement already satisfied: pyyaml in /opt/conda/lib/python3.7/site-packages (from dask->hypergbm) (5.4.1)
> Requirement already satisfied: locket in /opt/conda/lib/python3.7/site-packages (from partd>=0.3.10->dask->hypergbm) (0.2.1)
> Collecting dask-glm>=0.2.0
> Downloading dask_glm-0.2.0-py2.py3-none-any.whl (12 kB)
> Requirement already satisfied: multipledispatch>=0.4.9 in /opt/conda/lib/python3.7/site-packages (from dask-ml->hypergbm) (0.6.0)
> Requirement already satisfied: numba>=0.51.0 in /opt/conda/lib/python3.7/site-packages (from dask-ml->hypergbm) (0.53.1)
> Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /opt/conda/lib/python3.7/site-packages (from distributed->hypergbm) (2.4.0)
> Requirement already satisfied: psutil>=5.0 in /opt/conda/lib/python3.7/site-packages (from distributed->hypergbm) (5.8.0)
> Requirement already satisfied: tornado>=5 in /opt/conda/lib/python3.7/site-packages (from distributed->hypergbm) (6.1)
> Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from distributed->hypergbm) (57.4.0)
> Requirement already satisfied: tblib>=1.6.0 in /opt/conda/lib/python3.7/site-packages (from distributed->hypergbm) (1.7.0)
> Requirement already satisfied: msgpack>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from distributed->hypergbm) (1.0.2)
> Requirement already satisfied: jinja2 in /opt/conda/lib/python3.7/site-packages (from distributed->hypergbm) (3.0.1)
> Requirement already satisfied: click>=6.6 in /opt/conda/lib/python3.7/site-packages (from distributed->hypergbm) (8.0.1)
> Requirement already satisfied: zict>=0.1.3 in /opt/conda/lib/python3.7/site-packages (from distributed->hypergbm) (2.0.0)
> Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.7/site-packages (from click>=6.6->distributed->hypergbm) (3.4.0)
> Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in /opt/conda/lib/python3.7/site-packages (from numba>=0.51.0->dask-ml->hypergbm) (0.36.0)
> Requirement already satisfied: heapdict in /opt/conda/lib/python3.7/site-packages (from zict>=0.1.3->distributed->hypergbm) (1.0.1)
> Requirement already satisfied: typing-extensions>=3.6.4 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->click>=6.6->distributed->hypergbm) (3.7.4.3)
> Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->click>=6.6->distributed->hypergbm) (3.5.0)
> Requirement already satisfied: backcall in /opt/conda/lib/python3.7/site-packages (from ipython->hypernets==0.2.3->hypergbm) (0.2.0)
> Requirement already satisfied: decorator in /opt/conda/lib/python3.7/site-packages (from ipython->hypernets==0.2.3->hypergbm) (5.0.9)
> Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.7/site-packages (from ipython->hypernets==0.2.3->hypergbm) (4.8.0)
> Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from ipython->hypernets==0.2.3->hypergbm) (3.0.19)
> Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.7/site-packages (from ipython->hypernets==0.2.3->hypergbm) (0.1.2)
> Requirement already satisfied: pygments in /opt/conda/lib/python3.7/site-packages (from ipython->hypernets==0.2.3->hypergbm) (2.10.0)
> Requirement already satisfied: pickleshare in /opt/conda/lib/python3.7/site-packages (from ipython->hypernets==0.2.3->hypergbm) (0.7.5)
> Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.7/site-packages (from ipython->hypernets==0.2.3->hypergbm) (0.18.0)
> Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.7/site-packages (from jedi>=0.16->ipython->hypernets==0.2.3->hypergbm) (0.8.2)
> Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.7/site-packages (from pexpect>4.3->ipython->hypernets==0.2.3->hypergbm) (0.7.0)
> Requirement already satisfied: wcwidth in /opt/conda/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->hypernets==0.2.3->hypergbm) (0.2.5)
> Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.7/site-packages (from traitlets->hypernets==0.2.3->hypergbm) (0.2.0)
> Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.7/site-packages (from jinja2->distributed->hypergbm) (2.0.1)
> Requirement already satisfied: tenacity>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from plotly->hypergbm) (8.0.1)
> Building wheels for collected packages: python-geohash
> Building wheel for python-geohash (setup.py) ... done
> Created wheel for python-geohash: filename=python_geohash-0.8.5-cp37-cp37m-linux_x86_64.whl size=50692 sha256=0e0dc40b118fd1a5d26f093ec91dfc5cfbe771e34e3f469b9a788f8100ba7926
> Stored in directory: /root/.cache/pip/wheels/ea/62/7a/e8b943f1d8025cd93a93928a162319e56843301c8c06610ffe
> Successfully built python-geohash
> Installing collected packages: scikit-learn, seaborn, python-geohash, dask-glm, hypernets, dask-ml, hypergbm
> Attempting uninstall: scikit-learn
> Found existing installation: scikit-learn 0.23.2
> Uninstalling scikit-learn-0.23.2:
> Successfully uninstalled scikit-learn-0.23.2
> Attempting uninstall: seaborn
> Found existing installation: seaborn 0.11.2
> Uninstalling seaborn-0.11.2:
> Successfully uninstalled seaborn-0.11.2
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> pdpbox 0.2.1 requires matplotlib==3.1.1, but you have matplotlib 3.4.3 which is incompatible.
> hypertools 0.7.0 requires scikit-learn!=0.22,<0.24,>=0.19.1, but you have scikit-learn 1.0 which is incompatible.
> Successfully installed dask-glm-0.2.0 dask-ml-1.9.0 hypergbm-0.2.3 hypernets-0.2.3 python-geohash-0.8.5 scikit-learn-1.0 seaborn-0.11.0
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

> AttributeError Traceback (most recent call last)
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in dep_map(self)
> 3015 try:
> -> 3016 return self.__dep_map
> 3017 except AttributeError:
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in getattr(self, attr)
> 2812 if attr.startswith(''):
> -> 2813 raise AttributeError(attr)
> 2814 return getattr(self._provider, attr)
> AttributeError: _DistInfoDistribution__dep_map
> During handling of the above exception, another exception occurred:
> AttributeError Traceback (most recent call last)
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in _parsed_pkg_info(self)
> 3006 try:
> -> 3007 return self.pkg_info
> 3008 except AttributeError:
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in getattr(self, attr)
> 2812 if attr.startswith(''):
> -> 2813 raise AttributeError(attr)
> 2814 return getattr(self._provider, attr)
> AttributeError: _pkg_info
> During handling of the above exception, another exception occurred:
> FileNotFoundError Traceback (most recent call last)
> /tmp/ipykernel_43/4208425762.py in
> ----> 1 import hypergbm
> /opt/conda/lib/python3.7/site-packages/hypergbm/init.py in
> 4
> 5 """
> ----> 6 from hypernets.experiment import CompeteExperiment
> 7 from .hyper_gbm import HyperGBM, HyperGBMEstimator, HyperGBMExplainer, HyperEstimator, HyperModel
> 8 from .experiment import make_experiment
> /opt/conda/lib/python3.7/site-packages/hypernets/experiment/init.py in
> 7 from ._experiment import Experiment, ExperimentCallback
> 8 from .general import GeneralExperiment
> ----> 9 from .compete import CompeteExperiment, SteppedExperiment, StepNames
> 10 from ._callback import ConsoleCallback, SimpleNotebookCallback
> 11 from ._maker import make_experiment
> /opt/conda/lib/python3.7/site-packages/hypernets/experiment/compete.py in
> 19 from hypernets.core import set_random_state
> 20 from hypernets.experiment import Experiment
> ---> 21 from hypernets.tabular import dask_ex as dex, column_selector as cs
> 22 from hypernets.tabular import drift_detection as dd, feature_importance as fi, pseudo_labeling as pl
> 23 from hypernets.tabular.cache import cache
> /opt/conda/lib/python3.7/site-packages/hypernets/tabular/dask_ex/init.py in
> 18
> 19 try:
> ---> 20 import dask_ml.preprocessing as dm_pre
> 21 import dask_ml.model_selection as dm_sel
> 22
> /opt/conda/lib/python3.7/site-packages/dask_ml/init.py in
> 7
> 8 try:
> ----> 9 version = get_distribution(name).version
> 10 all.append("version")
> 11 except DistributionNotFound:
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in get_distribution(dist)
> 464 dist = Requirement.parse(dist)
> 465 if isinstance(dist, Requirement):
> --> 466 dist = get_provider(dist)
> 467 if not isinstance(dist, Distribution):
> 468 raise TypeError("Expected string, Requirement, or Distribution", dist)
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in get_provider(moduleOrReq)
> 340 """Return an IResourceProvider for the named module or requirement"""
> 341 if isinstance(moduleOrReq, Requirement):
> --> 342 return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
> 343 try:
> 344 module = sys.modules[moduleOrReq]
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in require(self, *requirements)
> 884 included, even if they were already activated in this working set.
> 885 """
> --> 886 needed = self.resolve(parse_requirements(requirements))
> 887
> 888 for dist in needed:
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
> 778
> 779 # push the new requirements onto the stack
> --> 780 new_requirements = dist.requires(req.extras)[::-1]
> 781 requirements.extend(new_requirements)
> 782
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in requires(self, extras)
> 2732 def requires(self, extras=()):
> 2733 """List of Requirements needed for this distro if extras are used"""
> -> 2734 dm = self._dep_map
> 2735 deps = []
> 2736 deps.extend(dm.get(None, ()))
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in _dep_map(self)
> 3016 return self.__dep_map
> 3017 except AttributeError:
> -> 3018 self.__dep_map = self._compute_dependencies()
> 3019 return self.__dep_map
> 3020
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in _compute_dependencies(self)
> 3025 reqs = []
> 3026 # Including any condition expressions
> -> 3027 for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
> 3028 reqs.extend(parse_requirements(req))
> 3029
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in _parsed_pkg_info(self)
> 3007 return self._pkg_info
> 3008 except AttributeError:
> -> 3009 metadata = self.get_metadata(self.PKG_INFO)
> 3010 self._pkg_info = email.parser.Parser().parsestr(metadata)
> 3011 return self._pkg_info
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in get_metadata(self, name)
> 1405 return ""
> 1406 path = self._get_metadata_path(name)
> -> 1407 value = self._get(path)
> 1408 try:
> 1409 return value.decode('utf-8')
> /opt/conda/lib/python3.7/site-packages/pkg_resources/init.py in _get(self, path)
> 1609
> 1610 def _get(self, path):
> -> 1611 with open(path, 'rb') as stream:
> 1612 return stream.read()
> 1613
> FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/scikit_learn-0.23.2.dist-info/METADATA'

**Comment by wuziqian** [comment]
thanks, And i  give a try as you said,  i got another error, the error is like :

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in _dep_map(self)
>    3015         try:
> -> 3016             return self.__dep_map
>    3017         except AttributeError:
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in __getattr__(self, attr)
>    2812         if attr.startswith('_'):
> -> 2813             raise AttributeError(attr)
>    2814         return getattr(self._provider, attr)
> 
> AttributeError: _DistInfoDistribution__dep_map
> 
> During handling of the above exception, another exception occurred:
> 
> AttributeError                            Traceback (most recent call last)
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in _parsed_pkg_info(self)
>    3006         try:
> -> 3007             return self._pkg_info
>    3008         except AttributeError:
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in __getattr__(self, attr)
>    2812         if attr.startswith('_'):
> -> 2813             raise AttributeError(attr)
>    2814         return getattr(self._provider, attr)
> 
> AttributeError: _pkg_info
> 
> During handling of the above exception, another exception occurred:
> 
> FileNotFoundError                         Traceback (most recent call last)
> /tmp/ipykernel_69/4208425762.py in <module>
> ----> 1 import hypergbm
> 
> /opt/conda/lib/python3.7/site-packages/hypergbm/__init__.py in <module>
>       4 
>       5 """
> ----> 6 from hypernets.experiment import CompeteExperiment
>       7 from .hyper_gbm import HyperGBM, HyperGBMEstimator, HyperGBMExplainer, HyperEstimator, HyperModel
>       8 from .experiment import make_experiment
> 
> /opt/conda/lib/python3.7/site-packages/hypernets/experiment/__init__.py in <module>
>       7 from ._experiment import Experiment, ExperimentCallback
>       8 from .general import GeneralExperiment
> ----> 9 from .compete import CompeteExperiment, SteppedExperiment, StepNames
>      10 from ._callback import ConsoleCallback, SimpleNotebookCallback
>      11 from ._maker import make_experiment
> 
> /opt/conda/lib/python3.7/site-packages/hypernets/experiment/compete.py in <module>
>      19 from hypernets.core import set_random_state
>      20 from hypernets.experiment import Experiment
> ---> 21 from hypernets.tabular import dask_ex as dex, column_selector as cs
>      22 from hypernets.tabular import drift_detection as dd, feature_importance as fi, pseudo_labeling as pl
>      23 from hypernets.tabular.cache import cache
> 
> /opt/conda/lib/python3.7/site-packages/hypernets/tabular/dask_ex/__init__.py in <module>
>      18 
>      19 try:
> ---> 20     import dask_ml.preprocessing as dm_pre
>      21     import dask_ml.model_selection as dm_sel
>      22 
> 
> /opt/conda/lib/python3.7/site-packages/dask_ml/__init__.py in <module>
>       7 
>       8 try:
> ----> 9     __version__ = get_distribution(__name__).version
>      10     __all__.append("__version__")
>      11 except DistributionNotFound:
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in get_distribution(dist)
>     464         dist = Requirement.parse(dist)
>     465     if isinstance(dist, Requirement):
> --> 466         dist = get_provider(dist)
>     467     if not isinstance(dist, Distribution):
>     468         raise TypeError("Expected string, Requirement, or Distribution", dist)
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in get_provider(moduleOrReq)
>     340     """Return an IResourceProvider for the named module or requirement"""
>     341     if isinstance(moduleOrReq, Requirement):
> --> 342         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
>     343     try:
>     344         module = sys.modules[moduleOrReq]
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in require(self, *requirements)
>     884         included, even if they were already activated in this working set.
>     885         """
> --> 886         needed = self.resolve(parse_requirements(requirements))
>     887 
>     888         for dist in needed:
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
>     778 
>     779             # push the new requirements onto the stack
> --> 780             new_requirements = dist.requires(req.extras)[::-1]
>     781             requirements.extend(new_requirements)
>     782 
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in requires(self, extras)
>    2732     def requires(self, extras=()):
>    2733         """List of Requirements needed for this distro if `extras` are used"""
> -> 2734         dm = self._dep_map
>    2735         deps = []
>    2736         deps.extend(dm.get(None, ()))
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in _dep_map(self)
>    3016             return self.__dep_map
>    3017         except AttributeError:
> -> 3018             self.__dep_map = self._compute_dependencies()
>    3019             return self.__dep_map
>    3020 
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in _compute_dependencies(self)
>    3025         reqs = []
>    3026         # Including any condition expressions
> -> 3027         for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
>    3028             reqs.extend(parse_requirements(req))
>    3029 
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in _parsed_pkg_info(self)
>    3007             return self._pkg_info
>    3008         except AttributeError:
> -> 3009             metadata = self.get_metadata(self.PKG_INFO)
>    3010             self._pkg_info = email.parser.Parser().parsestr(metadata)
>    3011             return self._pkg_info
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in get_metadata(self, name)
>    1405             return ""
>    1406         path = self._get_metadata_path(name)
> -> 1407         value = self._get(path)
>    1408         try:
>    1409             return value.decode('utf-8')
> 
> /opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py in _get(self, path)
>    1609 
>    1610     def _get(self, path):
> -> 1611         with open(path, 'rb') as stream:
>    1612             return stream.read()
>    1613 
> 
> **FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/scikit_learn-0.23.2.dist-info/METADATA'**

**Comment by lixfz** [comment]
At current timestamp, kaggle python container installed scikit-learn 0.23.2 by default. To use it with HyperGBM 0.2.3, install HyperGBM with command:

```
pip install scikit-learn==0.23.2  hypergbm==0.2.3 
```

To use scikit-learn 0.24.2 with HyperGBM in kaggle container at current timestamp,  install HyperGBM with command:
```
pip install  --user scikit-learn==0.24.2 hypergbm==0.2.3 
```

Inspect your kaggle container and see `pip install --help` for more information.
