### ISSUE TITLE
how can i define a new reward_metric in make_experiment()?

### ISSUE THREAD

**Issue by flyleeee** [DataCanvasIO/HyperGBM#50]
I want to use a new evaluation criterion defined by myself.

**Comment by mokeeqian** [comment]
当使用自定义reward_metric时，出现如下报错：
```
ValueError: Can't clean for JSON: ......
```

**Comment by oaksharks** [comment]
@mokeeqian 现在可视化支持自定义reward_metric了，您可以master分支更新HyperGBM后重试。

**Comment by lixfz** [comment]
Since version 0.2.5, user can custimize reward_metric with python function. See [HyperGBM docs](https://hypergbm.readthedocs.io/en/latest/how_to/customize_reward_metric.html) for details.

**Comment by mokeeqian** [comment]
> @mokeeqian 现在可视化支持自定义reward_metric了，您可以master分支更新HyperGBM后重试。

ok，感谢！
