### ISSUE TITLE
安装失败，如下所示。但其实我电脑里有visual c++14环境

### ISSUE THREAD

**Issue by feiyangdezhu** [DataCanvasIO/HyperGBM#59]
Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying geohash.py -> build\lib.win-amd64-3.7
  copying quadtree.py -> build\lib.win-amd64-3.7
  copying jpgrid.py -> build\lib.win-amd64-3.7
  copying jpiarea.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_geohash' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for python-geohash

**Comment by Enpen** [comment]
For geohash, you can try to install it online. `pip install python-geohash`. 
For hypergbm, we recommend  install with pip as well. `pip install hypergbm`
