### ISSUE TITLE
How does HyperGBM works?

### ISSUE THREAD

**Issue by mokeeqian** [DataCanvasIO/HyperGBM#70]
Does HyperGBM's make_experiment return the best model?
How does it work on paramter tuning? It's say that, what's its seach space (e.g. in XGboost)???

**Comment by Enpen** [comment]
Hi,mokeeqian, thanks for using hyperGBM,
For Q1:
>exp = make_experiment() --->exp is a CompeteExperiment class
>estimator = exp.run() --->estimator is a Pipeline class including best model and some data preprocessing method and so on.
you can get best_model by _exp.hyper_model\_.get\_best\_trial()_ as well.

For Q2:
By default, we use evolutionary search algorithm + meta learner for hyperparameter search, About search space, you can check it from hypergbm.search_space.py. we define the search space like this, and You can customize your search space too :

> 'booster': Choice(['gbtree', 'dart']),
            'max_depth': Choice([3, 5, 7, 10]),
            'min_child_weight': Choice([1, 5, 10]),
            'gamma': Choice([0.5, 1, 1.5, 2, 5]),
            'reg_alpha': Choice([0.001, 0.01, 0.1, 1, 10, 100]),
            'reg_lambda': Choice([0.001, 0.01, 0.1, 0.5, 1]),
In addition to algorithm parameters, we also look for optimal data preprocessing methods. 

If you have any other questions, Please feel free to tell us.

**Comment by mokeeqian** [comment]
> Hi,mokeeqian, thanks for using hyperGBM, For Q1:
> 
> > exp = make_experiment() --->exp is a CompeteExperiment class
> > estimator = exp.run() --->estimator is a Pipeline class including best model and some data preprocessing method and so on.
> > you can get best_model by _exp.hyper_model_.get_best_trial()_ as well.
> 
> For Q2: By default, we use evolutionary search algorithm + meta learner for hyperparameter search, About search space, you can check it from hypergbm.search_space.py. we define the search space like this, and You can customize your search space too :
> 
> > 'booster': Choice(['gbtree', 'dart']),
> > 'max_depth': Choice([3, 5, 7, 10]),
> > 'min_child_weight': Choice([1, 5, 10]),
> > 'gamma': Choice([0.5, 1, 1.5, 2, 5]),
> > 'reg_alpha': Choice([0.001, 0.01, 0.1, 1, 10, 100]),
> > 'reg_lambda': Choice([0.001, 0.01, 0.1, 0.5, 1]),
> > In addition to algorithm parameters, we also look for optimal data preprocessing methods.
> 
> If you have any other questions, Please feel free to tell us.

okey, thanks a lot!
I have noticed that your hyperGBM's read the doc page has not contained apis to the framewrok.
I suggest to add the api usages to the page, thank you again!

**Comment by Enpen** [comment]
Thank you for your suggestion, we will consider this and it will be added soon.
