### ISSUE TITLE
could you please solve the problem on my installing?

### ISSUE THREAD

**Issue by huayu95** [DataCanvasIO/HyperGBM#71]
Hi, distinguished composer! I'm a freshman in machine learning. I want to use the hypergbm on dealing with a classification task. But after I pip intall hypergbm, I met some problem that made me fail to install the package. Could you please take a look and help me with the problem. I'll be greatly appreciated! 

 Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 657 kB/s
Building wheels for collected packages: jieba, python-geohash
  Building wheel for jieba (setup.py) ... done
  Created wheel for jieba: filename=jieba-0.42.1-py3-none-any.whl size=19314477 sha256=659d5db71012e50daa40cc083515d9987ee8e99ea451a3ea44db3582773fc490
  Stored in directory: c:\users\li-hy\appdata\local\pip\cache\wheels\24\aa\17\5bc7c72e9a37990a9620cc3aad0acad1564dcff6dbc2359de3
  Building wheel for python-geohash (setup.py) ... error
  **ERROR: Command errored out with exit status 1:**
   command: 'C:\aanaconda\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Li-hy\\AppData\\Local\\Temp\\pip-install-zidv_k76\\python-geohash_da12afeb154e40c388f7e2b935782a23\\setup.py'"'"'; __file__='"'"'C:\\Users\\Li-hy\\AppData\\Local\\Temp\\pip-install-zidv_k76\\python-geohash_da12afeb154e40c388f7e2b935782a23\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Li-hy\AppData\Local\Temp\pip-wheel-hx133l9c'
       cwd: C:\Users\Li-hy\AppData\Local\Temp\pip-install-zidv_k76\python-geohash_da12afeb154e40c388f7e2b935782a23\
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying geohash.py -> build\lib.win-amd64-3.7
  copying quadtree.py -> build\lib.win-amd64-3.7
  copying jpgrid.py -> build\lib.win-amd64-3.7
  copying jpiarea.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_geohash' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for python-geohash
  Running setup.py clean for python-geohash
Successfully built jieba
Failed to build python-geohash
Installing collected packages: packaging, jedi, llvmlite, distributed, seaborn, python-geohash, pyarrow, plotly, numba, lightgbm, featuretools, dask-glm, slicer, hypernets, dask-ml, catboost, shap, jieba, hypernets-jupyter-widget, hypergbm
  Attempting uninstall: packaging
    Found existing installation: packaging 20.9
    Uninstalling packaging-20.9:
      Successfully uninstalled packaging-20.9
  Attempting uninstall: jedi
    Found existing installation: jedi 0.14.1
    Uninstalling jedi-0.14.1:
      Successfully uninstalled jedi-0.14.1
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.31.0
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by huayu95** [comment]
I have solve the problem, thanks!

**Comment by Enpen** [comment]
Hi,huayu95, thanks for using hyperGBM.
There are some simple examples in  `hyperGBM.example` , you can learn from it. 
All comments are more than welcome while using hyperGBM.

**Comment by mokeeqian** [comment]
> I have solve the problem, thanks!

how did you do ?
waiting for your replay

**Comment by huayu95** [comment]
> 

I just downloaded the installed corresponding version of python-geohash and llvmlite  whl file.

**Comment by mokeeqian** [comment]
> > 
> 
> I just downloaded the installed the corresponding version of python-geohash and llvmlite whl file.

What about the ```Microsoft Visual C++ 14.0 is required```?
Have you do something else?

**Comment by huayu95** [comment]
> > > 
> > 
> > 
> > I just downloaded the installed the corresponding version of python-geohash and llvmlite whl file.
> 
> What about the `Microsoft Visual C++ 14.0 is required`? Have you do something else?

No, the Microsoft Visual C++ 14.0 is not dispensable. I just installed the corrsponding version package mentioned in the  warning.

**Comment by mokeeqian** [comment]
> 

okey, thank you a lot...

**Comment by zhangyuqi-1** [comment]
need
yum install gcc-c++
