### ISSUE TITLE
Is Cox regression available for xgboost in HyperGBM?

### ISSUE THREAD

**Issue by Jwenyi** [DataCanvasIO/HyperGBM#75]
Dear HyperGBM team,
I'd like to use xgboost to select features for my survival model. In xgboost original packages I find they already support Cox Proportional Hazard Regression for survival analyses (see https://github.com/dmlc/xgboost/blob/f9302a56fbdabb28d071ed9e402ca75e03673b4d/src/objective/regression_obj.cu#L273-L358).
I would like to know if Cox regression is available in HyperGBM, and how should I originize my input data for it, numpy structured array or something else (survival data has two labels)?
All the best,
Wenyi Jin

**Comment by jackguagua** [comment]
Sorry for the late reply. HyperGBM can't support Cox regression task yet.
