### ISSUE TITLE
AttributeError: 'CompeteExperiment' object has no attribute 'y_eval_pred'

### ISSUE THREAD

**Issue by zhangyuqi-1** [DataCanvasIO/HyperGBM#80]
当 webui=True 参数设定时
会报错 AttributeError: 'CompeteExperiment' object has no attribute 'y_eval_pred'

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\hypernets\experiment\_experiment.py", line 86, in run
    callback.experiment_start(self)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\hboard\callbacks.py", line 125, in experiment_start
    super(WebVisExperimentCallback, self).experiment_start(exp)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\hypernets\experiment\_callback.py", line 577, in experiment_start
    d = ExperimentExtractor(exp).extract()
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\hypernets\experiment\_extractor.py", line 671, in extract
    if self.is_evaluated():
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\hypernets\experiment\_extractor.py", line 657, in is_evaluated
    return self.exp.X_eval is not None and self.exp.y_eval is not None and self.exp.y_eval_pred is not None
AttributeError: 'CompeteExperiment' object has no attribute 'y_eval_pred'

**Comment by oaksharks** [comment]
您好，如何复现这个错误？您是如何安装的HyperGBM？您可以运行这个例子么？ https://github.com/DataCanvasIO/HyperGBM/blob/main/hypergbm/tests/run_web_visualization.py

**Comment by zhangyuqi-1** [comment]
是使用 pip install hypergbm[all]  这个命令安装的

experiment = make_experiment(
    train_data=xy_train, target='label',
    eval_data=xy_dev,
    test_data=xy_test,
    task='binary',
    reward_metric='logloss',
    cv=False,
    # webui=True,  # 当这里取消注释时，就会报错  ，或者不取消注释直接使用 jupyter运行时也会报错
)

一直想体验下可视化功能，但是一直在被这个报错困扰

**Comment by oaksharks** [comment]
试试将`eval_data=xy_dev,` 参数去掉能否运行？

**Comment by zhangyuqi-1** [comment]
experiment = make_experiment(
train_data=xy_train, target='label',
# eval_data=xy_dev,
test_data=xy_test,
task='binary',
reward_metric='logloss',
webui=True,
)
这样设置可以运行
experiment = make_experiment(
train_data=xy_train, target='label',
eval_data=xy_dev,
test_data=xy_test,
task='binary',
reward_metric='logloss',
# webui=True,
)
这样设置也可以运行


experiment = make_experiment(
train_data=xy_train, target='label',
eval_data=xy_dev,
test_data=xy_test,
task='binary',
reward_metric='logloss',
webui=True,
)
这样设置报错：AttributeError: 'CompeteExperiment' object has no attribute 'y_eval_pred'

**Comment by oaksharks** [comment]
看起来像是Callback加载顺序引起的问题。`CompeteExperiment`的属性`y_eval_pred`初始化在：

https://github.com/DataCanvasIO/Hypernets/blob/b111d084357989b115e1249796c232540144a131/hypernets/experiment/_callback.py#L328-L331

但是在控制实验可视化的Callback在该属性未初始化时读取了它。在我修复这个bug之前建议您不要在**使用可视化时使用`eval_data`参数**。这两个参数可以单独使用。

**Comment by zhangyuqi-1** [comment]
好的， 期待早日修复此问题，感谢您的回复。 HyperGBM很好用 ，非常感谢您的工作。

**Comment by oaksharks** [comment]
@zhangyuqi-1 现在可以通过更新master分支的Hypernets解决这个问题，更新方法：
1. 下载[Hypernets](https://github.com/DataCanvasIO/Hypernets.git) 最新的代码到本地并解压
2. 更新Hypernets
```
pip uninstall -y hypernets
cd Hypernets && pip install .
```

更新成功后您可以检查报错是否还在。
