### ISSUE TITLE
请问是如何处理nan值的

### ISSUE THREAD

**Issue by zhangyuqi-1** [DataCanvasIO/HyperGBM#81]
请问代码内部是如何处理nan值的，我知道 XGB、LGB包本身是支持数据带nan进行训练的，但是我想知道HyperGBM是否在进行训练前将nan做了一定的处理，还是直接输入模型进行训练，我应该在哪可以发现相关处理逻辑。

**Comment by lixfz** [comment]
In the default HyperGBM search space , nan will be transformed wih SimpleImputer, the strategy  will be selected from ['mean', 'median', 'constant', 'most_frequent']. 

See [search_space.py](/DataCanvasIO/HyperGBM/blob/main/hypergbm/search_space.py) and  [sklearn_ops.py](/DataCanvasIO/HyperGBM/blob/main/hypergbm/sklearn/sklearn_ops.py)  for more details.
