### ISSUE TITLE
Unable to view Model Selected Features

### ISSUE THREAD

**Issue by haykuhidavtyan** [DataCanvasIO/HyperGBM#83]
Hello. I trained an estimator with make_experiment setting the parameter feature_selection=True, however, the estimator.get_params() does not give me the selected features and I am unable to extract feature importances as well. 
**HyperGBM version - 0.2.5.2**

```
experiment = make_experiment(
                             train_data=train, target='Target', eval_data=test,
                             cv=True, num_folds=5,
                             reward_metric='auc', pos_label=1,
                             max_trials=2,
                             feature_selection=True,
                            feature_selection_threshold=0.0001,
                             drift_detection=True,
                             class_balancing='RandomUnderSampler',
                             njobs = -1)
estimator = experiment.run()
```
The estimator.get_params() gives the following ouput:
`{'memory': None,
 'steps': [('data_adaption', DataAdaptionStep(name='data_adaption')),
  ('data_clean',
   DataCleanStep(cv=True,
                 data_cleaner_args={'correct_object_dtype': True,
                                    'drop_columns': None,
                                    'drop_constant_columns': True,
                                    'drop_duplicated_columns': False,
                                    'drop_idness_columns': True,
                                    'drop_label_nan_rows': True,
                                    'int_convert_to': 'float', 'nan_chars': None,
                                    'reduce_mem_usage': False,
                                    'reserve_columns': None},
                 name='data_clean')),
  ('feature_selection',
   FeatureImportanceSelectionStep(name='feature_selection', number=15,
                                  quantile=None, strategy='number',
                                  threshold=None)),
  ('estimator',
   GreedyEnsemble(weight=[0.0, 1.0], scores=[0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832]))],
 'verbose': False,
 'data_adaption': DataAdaptionStep(name='data_adaption'),
 'data_clean': DataCleanStep(cv=True,
               data_cleaner_args={'correct_object_dtype': True,
                                  'drop_columns': None,
                                  'drop_constant_columns': True,
                                  'drop_duplicated_columns': False,
                                  'drop_idness_columns': True,
                                  'drop_label_nan_rows': True,
                                  'int_convert_to': 'float', 'nan_chars': None,
                                  'reduce_mem_usage': False,
                                  'reserve_columns': None},
               name='data_clean'),
 'feature_selection': FeatureImportanceSelectionStep(name='feature_selection', number=15,
                                quantile=None, strategy='number',
                                threshold=None),
 'estimator': GreedyEnsemble(weight=[0.0, 1.0], scores=[0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832, 0.7872902176075832]),
 'data_adaption__memory_limit': 0.05,
 'data_adaption__min_cols': 0.3,
 'data_adaption__name': 'data_adaption',
 'data_adaption__target': None,
 'data_clean__cv': True,
 'data_clean__data_cleaner_args': {'nan_chars': None,
  'correct_object_dtype': True,
  'drop_constant_columns': True,
  'drop_label_nan_rows': True,
  'drop_idness_columns': True,
  'drop_columns': None,
  'reserve_columns': None,
  'drop_duplicated_columns': False,
  'reduce_mem_usage': False,
  'int_convert_to': 'float'},
 'data_clean__name': 'data_clean',
 'data_clean__train_test_split_strategy': None,
 'feature_selection__name': 'feature_selection',
 'feature_selection__number': 15,
 'feature_selection__quantile': None,
 'feature_selection__strategy': 'number',
 'feature_selection__threshold': None}`

**Comment by lixfz** [comment]
The trained estimator is a sklearn Pipeline object, its`get_params()` returns the pipleline initliazation settings only. To get the fitted details, you need to inspect each step object.

To get the  `feature_selection` step  fitted information, call its 'get_fitted_params()' method please. In your experiment, you can get  fitted informationas the following:

```python
step_index=2
step_object=estimator.steps[step_index][1]
print(step_object.get_fitted_params())

```

You can get the step object from experiment also:

```python
step_object=experiment.get_step('feature_selection')
print(step_object.get_fitted_params())

```

**Comment by lixfz** [comment]
In jupyter notebook, you can inspect step information as the following:

![图片](https://user-images.githubusercontent.com/68989761/160535900-daa126d9-738c-44d4-8ef7-86e697a638af.png)

**Comment by haykuhidavtyan** [comment]
@lixfz thank you for your reply. The `get_step()` attribute for experiment works, however, when I just trained the model using `make_experiment()` and `estimator=experiment.run()` and used the code you provided me with, it brought the following error : 

`experiment = make_experiment(
                             train_data=train, target='RESPONSE_FLAG', eval_data=test,
#                              test_data = X_valid.copy(),
                             cv=True, num_folds=5,
                             reward_metric='auc', pos_label=1,
                             max_trials=2,
                             feature_selection=True,
                             feature_selection_threshold=0.0001,
                             drift_detection=True,
                             class_balancing='RandomUnderSampler',
                             njobs = -1)
estimator = experiment.run()

step_index=2
step_object=estimator.steps[step_index][1]
print(step_object.get_fitted_params())`

`AttributeError                            Traceback (most recent call last)
<ipython-input-32-1b445002ae8a> in <module>
      1 step_index=2
      2 step_object=estimator.steps[step_index][1]
----> 3 print(step_object.get_fitted_params())

AttributeError: 'GreedyEnsemble' object has no attribute 'get_fitted_params'

`

I want to be able to save the fitted estimator for future use and get all the fitted parameters after loading it.

**Comment by lixfz** [comment]
Inspect your trained estimator(pipeline) steps to get the index of `feature_selection`, and change the line `step_index=2`.

Please note that if all features were kept during the feature selection (no features was removed ),  the trained estimator would not include the  `feature_selection` step.

**Comment by haykuhidavtyan** [comment]
@lixfz I understand that I if features are not removed, the `feature_selection` step would be missing. The issue is, that the features in my training data are 151, and when I run the estimator, it shows in the Fitted Parameters `X_train.shape 	(3622779, 58), kept/dropped feature count 	58/0`. My guess is the features are removed during the Data Cleaning stage, however, I am still unable to get the final features and their importances.

**Comment by lixfz** [comment]
As you said, your  train_data shape is 36227798*151, it is a large dataset. I guess the data_adaption step removed some features to reduce memory usage. Inspect it with `experiment.get_step('data_adaption')`.

You can get the input feature names of each experiment step with `input_features_` attribute, for  example:
```python
for step in experiment.steps:
    print(step.name, step.input_features_)
```

At present, HyperGBM has no direct method to get the feature importances of the whole pipeline.
